### ISSUE TITLE
Error with zip - Win10 says invalid

### ISSUE THREAD

**Issue by peksum** [Reduced-Lens/Reduced-Lens-Wiki-Archive#1]
Hello and thank you for making the zip file. However Windows isn't able to open it, says it's invalid. Any idea why?
Thank you!

**Comment by nottnottloop** [comment]
Hi, thanks for the feedback. I just tried this and you are completely right - it's to do with the length of the file names. I have updated the README:

To download the archive as a zip file, look above for the green <> Code button above, click it and select Download ZIP. Then extract the file using [7-Zip](https://www.7-zip.org/) (recommended) or another zip archive program like [WinRAR](https://www.win-rar.com/start.html?&L=0). Using the default Windows unzip program won't work due to the file names of some files.
